#!/usr/bin/ruby

# Apple iOS profile service using Rack
# Copyright Kenley Cheung 2011
# Licensed under the Apache License, Version 2.0.
# See LICENSE file for details.

require 'rubygems'
require 'rack'
require 'openssl'

require 'apple-profile'

class ProfileService
  def initialize
    profile_options = {
      "ProfileIdentifier" => "com.example.configuration",
      "ProfileDisplayName" => "Example profile",
      "ProfileDescription" => "Example configuration profile generated by apple-profile.rb"
    }
    wifi_options = {
      "ProfileIdentifier" => "com.example.configuration.wifi",
      "ProfileDisplayName" => "Example wifi profile",
      "ProfileDescription" => "Example configuration for sample WiFi network.",
      "ssid" => "TestNet",
      "encryption" => "WPA2"
    }
    wifi_profile = AppleProfile::wifi_payload(wifi_options)
    @profile = AppleProfile::configuration_payload(nil, profile_options, Array.new(wifi_profile))
  end
  def call(env)
    [200, {"Content-Type" => "application/x-apple-aspen-config"}, Plist::Emit.dump(profile)]
  end
end

Rack::Handler::Mongrel.run ProfileService.new, :Port => 9292